fix(helm): Use curl to download the helm binary
deis/e2e-runner pull request #57
Opened 2016-10-14 19:27 UTC by kmala

2016-10-14 19:34 UTC, helgi commented
https://github.com/deis/workflow-e2e/blob/c7a5c459c4291a7cbbe5eaebe71e4b7eea2c3221/docker-test-integration.sh#L22-L41 good idea to keep downloading similar

2016-10-14 19:50 UTC, kmala commented
@helgi changed..or did you mean the whole logic of latest and all?

2016-10-14 20:41 UTC, helgi requested changes

2016-10-14 20:41 UTC, helgi commented on scripts/helm.sh
> +	curl -f --silent --show-error -I "${url}"
I'd drop this - that's just a `HEAD` request

2016-10-14 20:41 UTC, helgi commented on scripts/helm.sh
> +	curl -f --silent --show-error --retry 5 --retry-delay 10 -O "${url}"
Spacing is inconsistent

2016-10-14 20:42 UTC, helgi commented
@kmala what you did is what I meant :) bar the 2 changes I pointed out

2016-10-14 22:25 UTC, kmala commented on scripts/helm.sh
> +	curl -f --silent --show-error -I "${url}"
removed.

2016-10-14 22:25 UTC, kmala commented on scripts/helm.sh
> +	curl -f --silent --show-error --retry 5 --retry-delay 10 -O "${url}"
changed.

2016-10-15 00:38 UTC, helgi commented
You are good to go then!

On Friday, October 14, 2016, Keerthan Reddy Mala <notifications@github.com>
wrote:

> *@kmala* commented on this pull request.
> ------------------------------
>
> In scripts/helm.sh <https://github.com/deis/e2e-runner/pull/57>:
>
> > @@ -38,8 +38,41 @@ clean_cluster() {
>  # install the kubernetes helm binary.
>  install_helm() {
>    local helm_version=${HELM_VERSION:-canary}
> -  wget http://storage.googleapis.com/kubernetes-helm/helm-"${helm_version}"-linux-amd64.tar.gz
> +  local url=https://storage.googleapis.com/kubernetes-helm/helm-"${helm_version}"-linux-amd64.tar.gz
> +  # Download CLI, retry up to 5 times with 10 second delay between each
> +	echo "Installing Helm CLI version '${helm_version}' via url '${url}'"
> +	curl -f --silent --show-error -I "${url}"
> +	curl -f --silent --show-error --retry 5 --retry-delay 10 -O "${url}"
>
> changed.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/deis/e2e-runner/pull/57>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAETguxaX9SR_kf9KoH_kLtra6qn3IAGks5q0AF0gaJpZM4KXXAs>
> .
>

2016-10-17 15:45 UTC, merged